### ISSUE TITLE
How to fix the Unhandled Rejection Errors after initial screen?

### ISSUE THREAD

**Issue by kva-adrian** [Acuant/HTML#1]
1. I was attempting to work this on my localhost on my Windows 10 laptop. After the installation, the first page load loads asking to upload a clear picture. After 3 seconds, the page redirects to an error. 
![1](https://user-images.githubusercontent.com/46211118/59356892-73698380-8d47-11e9-9315-22ced0173248.png)

2. if I hit the close button on the top right, the screens goes to the same first page. I choose the passport option and take a picture. After the analyzing screen another error arises: 
![2](https://user-images.githubusercontent.com/46211118/59357092-d0fdd000-8d47-11e9-94c0-22f865e4ffd8.png)

I am wondering what is causing this and how can I solve it? Any assistance would be appreciated

**Comment by chaojie-airwallex** [comment]
i also encounter this error

**Comment by kva-adrian** [comment]
>  i also encounter this error
@chaojie-airwallex 

So Acuant ahd mentioned the **only** AppID Endpoint should be changed ".eu" as I am based in Asia. `REACT_APP_ID_ENDPOINT=https://services.assureid.eu`

Then, i followed the issues that came up in the browser inspect element console.
In the _src_ folder in _App.js_ (at the top):
1. I commented/removed `import '@babel/polyfill';`  
2. I then added `import "core-js/stable";` and `import "regenerator-runtime/runtime";`

If I remember correctly, after the changes the browser's Inspect Element Console showed less errors and the yellow warning messages indicated a connection was made. 
I continued with `npm run build` for deployment and tried the files and it worked. 

Let me know if this helps you.

**Comment by matt-banknovo** [comment]
Getting the same issue, any idea? Commenting out @babel/polyfill helps but there appears to be an issue when trying to setInstanceID

**Comment by matt-banknovo** [comment]
The response is `The caller was not authenticated by the service.` do we need some form of authentication?

**Comment by vgargacuant** [comment]
Hello, can you please raise the issue on Acuant support portal so that our support staff can assist. 

https://support.acuant.com/
